node:
  id: 1

watcher:
  linger: 3s
  period: 5s
  batch-size: 50

logging:
  level:
    account: DEBUG
    org:
      hibernate:
        SQL: DEBUG

server:
  port: 18002

spring:
  application:
    name: account-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://mysql-host:3306/account?useSSL=false
    username: root
    password: root
  cloud:
    zookeeper:
      connect-string: zoo1:2181,zoo2:2181

feign:
  hystrix:
    enabled: true
